const hotels = [
  {
    id: "1",
    name: "Studio F3",
    location: "Mylapore,Chennai",
    price: 15000,
    image: require("../assets/studio1.webp"),
    reviews: 99,
    details: `We are Studio F3 from Chennai. With great experience in the wedding industry, we have a team with vast experience and relevant expertise in "Photography" industry. We provide exceptional services that will definitely give a treat to your eyes. We promise on capturing the best memories of your event. We will make sure that you cherish these special moments all your life. If you want to capture those special moments with your guests, we are your best choice. Say goodbye to old school photography and give us a chance to freeze the best moments in an innovative way. We promise you that your experience would be the best because of our personalized services.  We don’t believe in giving you an ordinary service, but an extraordinary experience that will make you come back to us again and again.For queries, information and special offers, contact us via CLICK. Your story, Our way!`,
  },
  {
    id: "2",
    name: "FlyHigh Media",
    location: "Guindy,Chennai",
    price: 20000,
    reviews: 102,
    image: require("../assets/studio2.webp"),
    details: `We are FlyHigh Media based in Chennai. My team and I have been working since 2018 and have covered 600 weddings till now. Photographs take you down the world of fond memories and therefore they should be impeccable in totality. We provide Helicam, Traditional Videography, Candid Videography, Traditional Photography, Candid Photography, Wedding Album, Wedding Montage, Crane Photography, Jimmy Jib, LED Wall, Photo booth, Instant Photos, Spot mixing, Live Stream, 3D Video, Post-wedding, Pre-wedding, Save the date video, Still Photography, Highlight reel, Wedding Movie photography services with the best professionals in the industry.`,
  },
  {
    id: "3",
    name: "Photon Talkies",
    location: "Nungambakkam,Chennai",
    price: 17000,
    reviews: 220,
    image: require("../assets/studio3.jpg"),
    details: `We are Photon Talkies from Chennai. With great experience in the wedding industry, we have a team with vast experience and relevant expertise in "Photography" industry. We provide exceptional services that will definitely give a treat to your eyes. We promise on capturing the best memories of your event. We will make sure that you cherish these special moments all your life. If you want to capture those special moments with your guests, we are your best choice. Say goodbye to old school photography and give us a chance to freeze the best moments in an innovative way. We promise you that your experience would be the best because of our personalized services.  We don’t believe in giving you an ordinary service, but an extraordinary experience that will make you come back to us again and again.For queries, information and special offers, contact us via CLICK. Your story, Our way!`,
  },
  {
    id: "4",
    name: "Light Studio",
    location: "Anna Nagar,Chennai",
    price: 28000,
    reviews: 48,
    image: require("../assets/studio4.jpg"),
    details: `We are Light Studios based in Chennai. My team and I have been working since 2018 and have covered 600 weddings till now. Photographs take you down the world of fond memories and therefore they should be impeccable in totality. We provide Helicam, Traditional Videography, Candid Videography, Traditional Photography, Candid Photography, Wedding Album, Wedding Montage, Crane Photography, Jimmy Jib, LED Wall, Photo booth, Instant Photos, Spot mixing, Live Stream, 3D Video, Post-wedding, Pre-wedding, Save the date video, Still Photography, Highlight reel, Wedding Movie photography services with the best professionals in the industry.`,
  },
  {
    id: "5",
    name: "Sony Digital",
    location: "T-Nagar,Chennai",
    price: 25000,
    reviews: 178,
    image: require("../assets/studio5.jpeg"),
    details: `We are Sony Digital from Chennai. With great experience in the wedding industry, we have a team with vast experience and relevant expertise in "Photography" industry. We provide exceptional services that will definitely give a treat to your eyes. We promise on capturing the best memories of your event. We will make sure that you cherish these special moments all your life. If you want to capture those special moments with your guests, we are your best choice. Say goodbye to old school photography and give us a chance to freeze the best moments in an innovative way. We promise you that your experience would be the best because of our personalized services.  We don’t believe in giving you an ordinary service, but an extraordinary experience that will make you come back to us again and again.For queries, information and special offers, contact us via CLICK. Your story, Our way!`,
  },
  {
    id: "6",
    name: "Focuz Studios",
    location: "Mahabalipuram,Chennai",
    price: 40000,
    reviews: 178,
    image: require("../assets/studio6.jpg"),
    details: `We are Focuz Studios from Chennai. With great experience in the wedding industry, we have a team with vast experience and relevant expertise in "Photography" industry. We provide exceptional services that will definitely give a treat to your eyes. We promise on capturing the best memories of your event. We will make sure that you cherish these special moments all your life. If you want to capture those special moments with your guests, we are your best choice. Say goodbye to old school photography and give us a chance to freeze the best moments in an innovative way. We promise you that your experience would be the best because of our personalized services.  We don’t believe in giving you an ordinary service, but an extraordinary experience that will make you come back to us again and again.For queries, information and special offers, contact us via CLICK. Your story, Our way!`,
  },
];

export default hotels;
